name: FoliaPerms
version: '${version}'
main: kaiakk.foliaPerms.FoliaPerms
api-version: '1.19'
authors: [KaiakK]
description: A simple Folia-only permission manager with YAML storage, GUI editor, and advanced permission handling.
website: https://modrinth.com/plugin/foliaperms
folia-supported: true
load: STARTUP
softdepend: [PlaceholderAPI]

commands:
  fperm:
    description: "Manage FoliaPerms (groups/users/permissions)"
    usage: "/fperm <help|reload|gather|refresh|user|group|check|listperms>"
    permission: folia.perms
    permission-message: "You don't have permission to use this command."

permissions:
  folia.perms:
    description: "Allow use of FoliaPerms admin commands"
    default: op # given by default to server operators, so that there wouldn't be a lockout situation